import {StyleSheet} from 'react-native';
export const accountStyle = (theme: any) =>
  StyleSheet.create({
    container: {
      flex: 1,
      backgroundColor: theme.colors.background,
    },
    dialog: {
      backgroundColor: theme.colors.background,
      borderRadius: 0,
    },
    header: {
      alignItems: 'flex-start',
      padding: 30,
      flexDirection: 'column',
      gap: 12,
    },
    headerGlow: {
      width: '100%',
      height: '40%',
      flex: 1,
    },
    Text: {
      color: theme.colors.text,
      fontSize: 16,
      fontWeight: '700',
      fontFamily: 'Montserrat-Regular',
    },
    buttons: {
      width: '100%',
      justifyContent: 'flex-start',
    },
    cancel: {
      backgroundColor: theme.colors.secondary,
      width: '50%',
      color: '#ffffff',
      fontSize: 14,
      fontWeight: '700',
      padding: 8,
      lineHeight: 22,
      fontFamily: 'Montserrat-Regular',
      borderRadius: 0,
    },
    logout: {
      backgroundColor: theme.colors.primary,
      width: '50%',
      color: 'white',
      fontSize: 14,
      fontWeight: '700',
      padding: 8,
      lineHeight: 22,
      fontFamily: 'Montserrat-Regular',
      borderRadius: 0,
    },
    title1: {
      fontSize: 16,
      fontWeight: '700',
      fontFamily: 'Montserrat-Regular',
      color: theme.colors.text,
    },
    editProfile: {
      borderColor: '#888888',
      borderWidth: 1,
      borderRadius: 18,
      paddingHorizontal: 12,
      paddingVertical: 8,
      flexDirection: 'row',
      backgroundColor: theme.colors.background,
      justifyContent: 'center',
      alignItems: 'center',
      gap: 5,
    },
    edit: {
      color: theme.colors.text,
      fontSize: 12,
      fontWeight: 'medium',
      fontFamily: 'Montserrat-Regular',
      letterSpacing: 1,
    },
    title: {
      fontSize: 24,
      fontWeight: 'bold',
      marginBottom: 8,
    },
    headerRow: {
      flexDirection: 'row',
      justifyContent: 'space-between',
      alignItems: 'flex-start',
      width: '90%',
      margin: 'auto',
    },
    profileContainer: {
      alignItems: 'center',
    },
    userName: {
      fontSize: 14,
      fontWeight: 'medium',
      fontFamily: 'Montserrat-Regular',
      color: '#888888',
    },
    userEmail: {
      fontSize: 14,
      fontWeight: 'medium',
      fontFamily: 'Montserrat-Regular',
      color: '#888888',
    },
    menuList: {
      padding: 16,
      backgroundColor: 'transparent',
    },
    menuItem: {
      padding: 20,
      borderRadius: 12,
      borderTopColor: theme.colors.border,
      borderTopWidth: 1,
    },
    menuRow: {
      flexDirection: 'row',
      justifyContent: 'space-between',
      alignItems: 'center',
    },
    menuLeft: {
      flexDirection: 'row',
      alignItems: 'center',
    },
    iconContainer: {
      width: 32,
      height: 32,
      borderRadius: 16,
      alignItems: 'center',
      justifyContent: 'center',
    },
    menuTitle: {
      fontSize: 14,
      marginLeft: 12,
      color: theme.colors.text,
    },
    profileImageWrapper: {
      width: 120,
      height: 120,
      borderRadius: 80,
      marginTop: 10,
      justifyContent: 'center',
      alignItems: 'center',
      alignSelf: 'center',
      position: 'relative',
    },
    iconOverlay: {
      position: 'absolute',
      bottom: 0,
      right: 0,
      backgroundColor: theme.colors.background,
      borderRadius: 10,
      padding: 3,
      justifyContent: 'center',
      alignItems: 'center',
      zIndex: 1000,
    },
    profileImage: {
      width: 120,
      height: 120,
      borderRadius: 80,
      backgroundColor: theme.colors.background,
    },
  });
