import {StyleSheet} from 'react-native';

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: '#000',
  },
  dialog: {
    backgroundColor: '#000000',
    borderRadius: 0,
  },
  header: {
    alignItems: 'flex-start',
    padding: 30,
    flexDirection: 'column',
    gap: 12,
  },
  headerGlow: {
    width: '100%',
    height: '40%',
    flex: 1,
  },
  Text: {
    color: '#fff',
    fontSize: 16,
    fontWeight: '700',
    fontFamily: 'Montserrat-Regular',
  },
  buttons: {
    width: '100%',
    justifyContent: 'flex-start',
  },
  cancel: {
    backgroundColor: '#242600',
    width: '50%',
    color: '#fff',
    fontSize: 14,
    fontWeight: '700',
    padding: 8,
    lineHeight: 22,
    fontFamily: 'Montserrat-Regular',
    borderRadius: 0,
  },
  logout: {
    backgroundColor: '#B2C000',
    width: '50%',
    color: '#000',
    fontSize: 14,
    fontWeight: '700',
    padding: 8,
    lineHeight: 22,
    fontFamily: 'Montserrat-Regular',
    borderRadius: 0,
  },
  title1: {
    fontSize: 16,
    fontWeight: '700',
    fontFamily: 'Montserrat-Regular',
    color: '#FFFFFF',
  },
  editProfile: {
    borderColor: '#888888',
    borderWidth: 1,
    borderRadius: 18,
    paddingHorizontal: 12,
    paddingVertical: 8,
    flexDirection: 'row',
    backgroundColor: '#191919',
    justifyContent: 'center',
    alignItems: 'center',
    gap: 5,
  },
  edit: {
    color: '#fff',
    fontSize: 12,
    fontWeight: 'medium',
    fontFamily: 'Montserrat-Regular',
    letterSpacing: 1,
  },
  title: {
    fontSize: 24,
    fontWeight: 'bold',
    marginBottom: 8,
  },
  headerRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'flex-start',
    width: '90%',
    margin: 'auto',
  },
  profileContainer: {
    alignItems: 'center',
  },
  userName: {
    fontSize: 14,
    fontWeight: 'medium',
    fontFamily: 'Montserrat-Regular',
    color: '#888888',
  },
  userEmail: {
    fontSize: 14,
    fontWeight: 'medium',
    fontFamily: 'Montserrat-Regular',
    color: '#888888',
  },
  menuList: {
    padding: 16,
    backgroundColor: 'transparent',
  },
  menuItem: {
    padding: 20,
    borderRadius: 12,
    borderTopColor: '#252525',
    borderTopWidth: 1,
  },
  menuRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
  },
  menuLeft: {
    flexDirection: 'row',
    alignItems: 'center',
  },
  iconContainer: {
    width: 32,
    height: 32,
    borderRadius: 16,
    alignItems: 'center',
    justifyContent: 'center',
  },
  menuTitle: {
    fontSize: 14,
    marginLeft: 12,
    color: '#FFF',
  },
  profileImageWrapper: {
    width: 120,
    height: 120,
    borderRadius: 80,
    marginTop: 10,
    justifyContent: 'center',
    alignItems: 'center',
    alignSelf: 'center',
    position: 'relative',
  },
  iconOverlay: {
    position: 'absolute',
    bottom: 0,
    right: 0,
    backgroundColor: '#0c0c0c',
    borderRadius: 10,
    padding: 3,
    justifyContent: 'center',
    alignItems: 'center',
    zIndex: 1000,
  },
  profileImage: {
    width: 120,
    height: 120,
    borderRadius: 80,
    backgroundColor: 'white',
  },
});
