import {StyleSheet} from 'react-native';

export const getStyles = (theme: any) =>
  StyleSheet.create({
    safeArea: {
      flex: 1,
    },
    bottomSheetContent: {
      padding: 16,
    },
    headContainer: {
      flexDirection: 'row',
      justifyContent: 'space-between',
    },
    name: {
      fontSize: 16,
      fontWeight: '600',
      fontFamily: 'Montserrat-Regular',
      color: '#888888',
      justifyContent: 'center',
      alignItems: 'center',
    },
    dialog: {
      backgroundColor: '#000000',
      borderRadius: 0,
    },
    menu: {
      flexDirection: 'row',
      gap: 10,
      alignItems: 'center',
      padding: 19,
    },
    detail: {
      flexDirection: 'row',
      gap: 5,
    },
    name1: {
      fontSize: 16,
      fontWeight: '700',
      fontFamily: 'Montserrat-Regular',
      color: theme.colors.text,
    },
    category: {
      flexDirection: 'row',
      gap: 10,
    },
    type: {
      borderColor: theme.colors.labelBorder1,
      paddingHorizontal: 12,
      paddingVertical: 4,
      borderWidth: 1,
      borderRadius: 20,
      color: theme.colors.labelBorder1,
      fontFamily: 'Montserrat-Regular',
      fontWeight: 'medium',
      fontSize: 10,
    },
    type1: {
      borderColor: theme.colors.labelBorder2,
      paddingHorizontal: 12,
      paddingVertical: 4,
      borderWidth: 1,
      borderRadius: 20,
      color: theme.colors.labelBorder2,
      fontFamily: 'Montserrat-Regular',
      fontWeight: 'medium',
      fontSize: 10,
    },
    card: {
      borderRadius: 0,
      overflow: 'hidden',
      flex: 1,
      margin: 8,
      backgroundColor: theme.colors.card,
    },
    heading: {
      color: theme.colors.text1,
      fontSize: 12,
      fontWeight: '700',
      fontFamily: 'Montserrat-Regular',
    },
    image: {
      width: '100%',
      height: 150,
    },
    addvenuebutton: {
      flexDirection: 'row',
      gap: 5,
      backgroundColor: theme.colors.surface,
      paddingHorizontal: 12,
      paddingVertical: 8,
      borderRadius: 20,
      justifyContent: 'center',
      alignItems: 'center',
      borderWidth: 1,
      borderColor: theme.colors.border1,
    },
    text: {
      color: theme.colors.text,
      fontSize: 12,
      fontFamily: 'Montserrat-Regular',
      fontWeight: '700',
    },
    bottomtext: {
      color: theme.colors.text,
      fontSize: 14,
      fontFamily: 'Montserrat-Regular',
      fontWeight: '600',
    },
    shadow: {
      shadowColor: '#000',
      shadowOffset: {width: 0, height: 3},
      shadowOpacity: 0.1,
      shadowRadius: 6,
      // elevation: 4,
    },
    venueName: {
      fontSize: 18,
      fontWeight: '600',
      marginBottom: 4,
    },
    chip: {
      backgroundColor: '#e0f7fa',
      color: '#00796b',
      alignSelf: 'flex-start',
      paddingHorizontal: 8,
      paddingVertical: 2,
      borderRadius: 12,
      fontSize: 12,
      marginBottom: 8,
    },
    cardText: {
      flex: 1,
      gap: 10,
      flexDirection: 'row',
      alignItems: 'center',
    },
    boldText: {
      fontWeight: '600',
    },
    locationText: {
      marginTop: 6,
      fontSize: 13,
      color: 'gray',
      flex: 1,
      gap: 10,
    },
    header: {
      flexDirection: 'row',
      justifyContent: 'space-between',
      alignItems: 'center',
      marginBottom: 10,
    },
    Text: {
      color: '#fff',
      fontSize: 16,
      fontWeight: '700',
      fontFamily: 'Montserrat-Regular',
    },
    buttons: {
      width: '100%',
      justifyContent: 'flex-start',
    },
    cancel: {
      backgroundColor: '#242600',
      width: '50%',
      color: '#fff',
      fontSize: 14,
      fontWeight: '700',
      padding: 8,
      lineHeight: 22,
      fontFamily: 'Montserrat-Regular',
      borderRadius: 0,
    },
    logout: {
      backgroundColor: '#B2C000',
      width: '50%',
      color: '#000',
      fontSize: 14,
      fontWeight: '700',
      padding: 8,
      lineHeight: 22,
      fontFamily: 'Montserrat-Regular',
      borderRadius: 0,
    },
    headerGlow: {
      width: '100%',
      height: '50%',
      flex: 1,
    },
    headerText: {
      fontSize: 16,
      fontFamily: 'Montserrat-Regular',
      color: theme.colors.text,
    },
    venueListContainer: {
      margin: 10,
      padding: 10,
      marginBottom: 40,
    },
  });
